name: trainingapp1
description: "Flutter Training Module"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.8
  another_flushbar: ^1.10.0
  path_provider: ^2.0.11
  sqflite: ^2.0.0+4
  crypto: ^3.0.0
  encrypt: ^5.0.0
  bcrypt:
  intl: ^0.19.0
  path: ^1.8.0
  image_cropper: ^8.0.2 #allows you to crop the image
  image_picker: ^1.1.2  #allows you to open the mobile's gallery and pick an image
  uuid:
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  permission_handler:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login_background.png
